  version: '3.1'

  services:

    db:
      image: postgres:latest
      restart: always
      ports:
        - '5432:5432'
      volumes:
        - ./data:/var/lib/postgres
      environment:
          POSTGRES_DATABASE: firstBase
          POSTGRES_USER: anton
          POSTGRES_PASSWORD: anton12345
