  version: '3.1'

  services:

    db:
      image: postgres:latest
      restart: always
      ports:
        - 8000:8080
      volumes:
        - ./data:/var/lib/postgres
      environment:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: anton12345

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080